language: generic
script: bash build_project.sh
notifications:
  email:
    recipients:
      - oualid.benazzouz@etu.univ-cotedazur.fr
      - cyril.marilier@etu.univ-cotedazur.fr
    on_success: always # default: change
    on_failure: always
branches:
  except:
    - preparatory-work