language: java
script: mvn clean package
notifications:
  email:
    recipients:
      - chihabeddine.aourinmouche@etu.univ-cotedazur.fr
      - oualid.benazzouz@etu.univ-cotedazur.fr
      - cyril.marilier@etu.univ-cotedazur.fr
    on_success: change
    on_failure: always
branches:
  except:
    - preparatory-work