sudo: required

language: java

services:
  - docker

before_script:
  - bash docker_login.sh projets2192co $DOCKER_PASSWORD
  - docker pull projets2192co/takenoko:server
  - docker run -d -p 8080:8080 -t projets2192co/takenoko:server
script:
  - cd takenoko-client
  - mvn clean package

notifications:
  email:
    recipients:
      - oualid.benazzouz@etu.univ-cotedazur.fr
      - cyril.marilier@etu.univ-cotedazur.fr
    on_success: always # default: change
    on_failure: always

branches:
  except:
    - preparatory-work
