language: java
script:
  # Launches the server...
  - cd takenoko-server
  - mvn exec:java -Dexec.args=4 &
  # Builds the project
  - cd ..
  - mvn clean package
notifications:
  email:
    recipients:
      - oualid.benazzouz@etu.univ-cotedazur.fr
      - cyril.marilier@etu.univ-cotedazur.fr
    on_success: always # default: change
    on_failure: always
branches:
  except:
    - preparatory-work