language: java
script: 
      - mvn clean package
      - mvn exec:java -Dexec.args=4
notifications:
  email:
    recipients:
      - chihabeddine.aourinmouche@etu.univ-cotedazur.fr
      - oualid.benazzouz@etu.univ-cotedazur.fr
      - cyril.marilier@etu.univ-cotedazur.fr
    on_success: always # default: change
    on_failure: always
branches:
  except:
    - preparatory-work