sudo: required

language: java

services:
  - docker

before_script:
  - ./takenoko-server/mvnw clean package
  - bash docker_login.sh
script:
  - docker pull projets2192co/takenoko:server
  - docker run -d -p 8080:8080 -t projets2192co/takenoko:server
after_script: ./takenoko-client/mvnw clean package

notifications:
  email:
    recipients:
      - oualid.benazzouz@etu.univ-cotedazur.fr
      - cyril.marilier@etu.univ-cotedazur.fr
    on_success: always # default: change
    on_failure: always

branches:
  except:
    - preparatory-work
